#ifndef __MESSAGE_QUEUE_H
#define __MESSAGE_QUEUE_H

#include "ltrx_compile_defines.h" /* Delivered with SDK. */
#include "bleSensor_module_defs.h" /* Automatically generated by make. */

struct message_queue;

struct message_queue* init_queue(void);
void destroy_queue(struct message_queue* s_queue);
bool new_message(struct message_queue* s_queue, void* value, size_t size);
bool get_message(struct message_queue* s_queue, void* value);

#endif
